### ISSUE TITLE
Incorrect interpretation of server error on --debug

### ISSUE THREAD

**Issue by pskaarup** [narirou/gulp-develop-server#10]
launching using `execArgv: ['--debug']` is interpreted wrongly as an error.
```
var devServerOpts;

devServerOpts = {
  path: path.join(binServer, 'main.js'),,
  execArgv: ['--debug']
};

gulp.task('server-start', function() {
  return devServer.listen(devServerOpts);
});

gulp.task('server-reload', function() {
  return devServer.restart(function(err) {
    if (err != null) {
      return console.log(err);
    } else {
      return livereload.reload();
    }
  });
});
```

```
$ gulp server-start
[23:47:50] Using gulpfile D:\Sync\git\untitled-gulp-build-system\generator\Gulpfile.js
[23:47:50] Starting 'server-start'...
[23:47:50] Finished 'server-start' after 8.47 ms
[23:47:50] Development server has error.
--- server starts running correctly ---
```

After inserting logging message in
```
// run callback with error message if the server has error
child.stderr.once( 'data', function( error ) {
  if( ! called && error ) {
    if( timer ) {
      timer = clearTimeout( timer );
    }
    var msg = 'Development server has error.';
    gutil.log( gutil.colors.red( msg ) );
    called = true;
    started( msg, callback );
  }
});
```
in gulp-develop-server `index.js` i found that error is at this point is a buffer pipe.
The code assumes that any content in `error` is an *error* even though `error` might be a empty pipe.

**Comment by narirou** [comment]
Hi, @pskaarup.
Thank you for the detailed report.
This error is caused by debug messages of the Node is to be piped to stderr.
I will fix this problem in the next version.

**Comment by narirou** [comment]
From 0.4.0, `options.errorMessage`(RegExp) added.
It will only check the specific error message that matched this option at start-up.
So I think this problem would be fiexed.
If there is a problem, please reopen the issue.
Thanks. :)
