### ISSUE TITLE
server.restart should restart server even when it's down

### ISSUE THREAD

**Issue by peleteiro** [narirou/gulp-develop-server#16]
When server process crash, server.reset does not work. It should start server even if it's down.

**Comment by neagle** [comment]
This seems like the problem behind an error I'm getting, too: "Development server already received restart requests."

This happens whenever I crash my development server (something that, naturally, happens quite a lot). And if I trigger a restart and it still has bad code (I _think_), then it won't restart the server until I stop the server manually and restart it.

**Comment by pwielgolaski** [comment]
As restart is just kill and listen if kill will not succeed, it will assume that it is in process of restart.
I did small change to use child.connected property to make sure if it makes sense to kill process at all.

It can be done in different way to observer exit event for child process if it is closed abnormally.

**Comment by GriffinSauce** [comment]
+1
