### ISSUE TITLE
Arguments to the script

### ISSUE THREAD

**Issue by xduseko** [narirou/gulp-develop-server#7]
There is no way to pass arguments to the script. Instead, arguments can be passed only to the node.js executable using option execArgv.
> var server = require('gulp-develop-server');
> server.listen({
> path: './stub/server.js',
> execArgv : ['--param']
> });

Expected behaviour:
> "C:\Program Files\nodejs\node.exe" ./stub/server.js  --param

Actual behaviour:
> "C:\Program Files\nodejs\node.exe" --param ./stub/server.js

**Comment by pskaarup** [comment]
`execArgv` is used to pass arguments to node. i.e. `--debug`. 

Use `env` to pass options to your app.
This will put the options on `process.env`, which wile not ideal is usable in development.

**Comment by PinkaminaDianePie** [comment]
without arguments in cli this module useless for any console-like tools. in many scenarios cli args more preferable than process.env

**Comment by pskaarup** [comment]
You are right but, I think this tool was created to launch node web-servers like express. It seems people like to use NODE_ENV to set env flags.

**Comment by PinkaminaDianePie** [comment]
not everytime. for example my SERVER has some commands:

  Usage: app [options] [command]

  Commands:

    listen                   inititalize app and listen port
    install                  install app in new environment
    module [options] <name>  create new module with given name by template
    bump [options] <module>  create new controller for given module by template
    migration <name>         create new migration template for module with given name
    *                        help

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

So, i dont have separate tools for app, if i need to start server i write "node app.js listen". If i need to create migration or new module template i use server as a command line tool. it works fine with process managers like PM2, but i can't start server from this gulp module.

**Comment by narirou** [comment]
Hello.
Thank you for reports.
I now understand the cause of this problem. (sorry...)
So we added `options.args` for the client argument.

```javascript
server.listen({
    path: './stub/server.js',
    args: ['--cliant-args'],
    execArgv : ['--harmony']
});
```
will parse
> node --harmony ./stub/server.js --cliant-args

If there is no problem I will merge this fix in the next version.

**Comment by PinkaminaDianePie** [comment]
yeah, its just what i need, thank you!

**Comment by narirou** [comment]
If there is a problem, please reopen the issue.
Thanks.
